### PR TITLE
Allow recipes from subdirectories

### PR DESCRIPTION
**Pull request by madebr**
- package tools need to get the recipe from the correct path
- This allows building bincrafters/conan-flex#4 on my machine

### CODE REVIEW

**Comment by uilianries** [comment]
Is it not possible only using tools.chdir, instead of passing the recipe path?

**Comment by madebr** [comment]
The flex pr has 2 sub directories containing the recipes with the common code in the main directory.
When using docker, it needs to _mount_ the main directory instead of only the sub directory.
(mounting only the sub directory would hide the main directory in the docker instance)

**Comment by SSE4** [comment]
@uilianries WDYT, should we merge this one?
BTW, CI seems to be stuck for unknown reason

**Comment by uilianries** [comment]
Seems weird, but I think it's an event error, since Travis is green:

https://travis-ci.com/bincrafters/bincrafters-package-tools/builds/105447388

I think it's okay, since CPT is up-to-date in our CI.

**Pull request merged**
