### PR TITLE
Add **kwargs to functions that return a builder + remove shebang

### PR DESCRIPTION
**Pull request by madebr**
Adding `**kwargs` is useful when a build script needs to pass non-standard arguments to the constructor of `ConanMultiPackager`.

For example: https://github.com/bincrafters/conan-flex/pull/4#issuecomment-465173462

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries any ideas on this error?
```
3.7 is not installed; attempting download
Downloading archive: https://travis-ci-python-archives.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
0.21s$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

**Comment by SSE4** [comment]
@uilianries ping :)

**Comment by uilianries** [comment]
@SSE4 I can't download python 2.7 too

```
wget https://travis-ci-python-archives.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
--2019-03-14 08:20:03--  https://travis-ci-python-archives.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving travis-ci-python-archives.global.ssl.fastly.net (travis-ci-python-archives.global.ssl.fastly.net)... 151.101.93.194
Connecting to travis-ci-python-archives.global.ssl.fastly.net (travis-ci-python-archives.global.ssl.fastly.net)|151.101.93.194|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-03-14 08:20:04 ERROR 403: Forbidden.
```

I think Travis is not totally recovered from yesterday. But there is no error message on https://www.traviscistatus.com/

I'll send an email relating this error.

**Comment by uilianries** [comment]
I sent the email. Let's wait for an answer.

**Comment by uilianries** [comment]
That's weird, Python 3.7 is listed in the [documentation](https://docs.travis-ci.com/user/languages/python/). Also, I can download both python-3.6 and python-3.7-dev

**Comment by madebr** [comment]
Maybe the missing `dist` option?

**Comment by uilianries** [comment]
@madebr Yes, it makes sense.

**Comment by uilianries** [comment]
done! I just included the linux distro. Let's wait for the CI result.

**Comment by madebr** [comment]
Is this a go then?

**Comment by uilianries** [comment]
@madebr merged! Thanks! I gonna release a new version soon

**Comment by uilianries** [comment]
Done: https://github.com/bincrafters/bincrafters-package-tools/releases/tag/0.17.10

Let's wait the new release on Pypi

**Comment by madebr** [comment]
@uilianries pypi is still at 0.17.9
See https://pypi.org/project/bincrafters-package-tools/

**Comment by uilianries** [comment]
lemme check what happened

**Comment by uilianries** [comment]
@madebr Fixed, but need to wait for CI job:

https://travis-ci.com/bincrafters/bincrafters-package-tools/jobs/186758624

Thanks for reporting!

**Comment by uilianries** [comment]
Done!

https://pypi.org/project/bincrafters-package-tools/0.17.10/

**Pull request merged**
