### PR TITLE
github actions support

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by Croydon** [comment]
Where are those env variables documented?

**Comment by ericLemanissier** [comment]
https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables

**Comment by Croydon** [comment]
Did you check what the value of `GITHUB_REPOSITORY` is for pull requests?

I guess similar to the AZP logic, we need some form of

```
if pull_request then
   use GITHUB_BASE_REF
```

**Comment by ericLemanissier** [comment]
I just did a cross repo PR test here: https://github.com/bincrafters/conan-qt/pull/43/checks?check_run_id=257640481
as can be seen during "install" phase, we still have GITHUB_REPOSITORY=bincrafters/conan-qt

**Comment by Croydon** [comment]
Sorry, I wrote `GITHUB_REPOSITORY` but I meant `GITHUB_REF`

Anyway, you patched in the way I meant it 👍

**Comment by uilianries** [comment]
Nice! Cool feature!

**Pull request merged**
