### PR TITLE
add gcc 10, clang 10 and clang 11

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by Croydon** [comment]
Should we wait until CCI adds builds for those compilers? If we merge now most build jobs will fail because of missing binaries

**Comment by ericLemanissier** [comment]
Yes, clearly. My fingers did this PR in autopilot, my brain is long asleep because it's Friday evening !

**Comment by ericLemanissier** [comment]
I also added clang 11 and apple-clang 12. I'm not sure which configuration has to be removed

**Comment by Croydon** [comment]
Let's not remove anything right now, but rather wait until our infrastructure / resources are clear and CCI decides too what configurations they support

**Comment by Croydon** [comment]
There are merge conflicts

**Comment by ericLemanissier** [comment]
really ? Github tells me `This branch has no conflicts with the base branch` and shows me the "merge pull request" button ?

**Comment by Croydon** [comment]
Interesting. I'm getting this

```
This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch. 
```

**Pull request merged**
